### ISSUE TITLE
Для чего тегу body присваивать id с одноименным именем

### ISSUE THREAD

**Issue by ikuchmin** [WFS-1/frontend-school#2]
Нам известно, что тег body должен быть единственным на странице. Что по своей сути гарантирует его уникальность.
Если опустить id для body и изменить селектор в css, то страница по прежнему будет отображаться корректно.
Не является ли это сущностью сверх необходимого? Какое преимущество дает использование id?

**Comment by DonRai** [comment]
@ikuchmin это просто тествый пример, надо было показать, что можно использовать идентификаторы, поставив его на тег боди, заодно проиллюстрировал его уникальность.
